/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CvRouteImport } from './routes/cv'
import { Route as ConceptsGlitchIndexRouteImport } from './routes/concepts.glitch.index'
import { Route as ConceptsGlitchFieldRouteImport } from './routes/concepts.glitch.field'
import { Route as ConceptsGlitchShardsRouteImport } from './routes/concepts.glitch.shards'
import { Route as ConceptsGlitchTraceRouteImport } from './routes/concepts.glitch.trace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsGlitchIndexRoute = ConceptsGlitchIndexRouteImport.update({
  id: '/concepts/glitch/',
  path: '/concepts/glitch/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsGlitchFieldRoute = ConceptsGlitchFieldRouteImport.update({
  id: '/concepts/glitch/field',
  path: '/concepts/glitch/field',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsGlitchShardsRoute = ConceptsGlitchShardsRouteImport.update({
  id: '/concepts/glitch/shards',
  path: '/concepts/glitch/shards',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsGlitchTraceRoute = ConceptsGlitchTraceRouteImport.update({
  id: '/concepts/glitch/trace',
  path: '/concepts/glitch/trace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/concepts/glitch/field': typeof ConceptsGlitchFieldRoute
  '/concepts/glitch/shards': typeof ConceptsGlitchShardsRoute
  '/concepts/glitch/trace': typeof ConceptsGlitchTraceRoute
  '/concepts/glitch/': typeof ConceptsGlitchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/concepts/glitch/field': typeof ConceptsGlitchFieldRoute
  '/concepts/glitch/shards': typeof ConceptsGlitchShardsRoute
  '/concepts/glitch/trace': typeof ConceptsGlitchTraceRoute
  '/concepts/glitch': typeof ConceptsGlitchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/concepts/glitch/field': typeof ConceptsGlitchFieldRoute
  '/concepts/glitch/shards': typeof ConceptsGlitchShardsRoute
  '/concepts/glitch/trace': typeof ConceptsGlitchTraceRoute
  '/concepts/glitch/': typeof ConceptsGlitchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv'
    | '/concepts/glitch/field'
    | '/concepts/glitch/shards'
    | '/concepts/glitch/trace'
    | '/concepts/glitch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv'
    | '/concepts/glitch/field'
    | '/concepts/glitch/shards'
    | '/concepts/glitch/trace'
    | '/concepts/glitch'
  id:
    | '__root__'
    | '/'
    | '/cv'
    | '/concepts/glitch/field'
    | '/concepts/glitch/shards'
    | '/concepts/glitch/trace'
    | '/concepts/glitch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  ConceptsGlitchFieldRoute: typeof ConceptsGlitchFieldRoute
  ConceptsGlitchShardsRoute: typeof ConceptsGlitchShardsRoute
  ConceptsGlitchTraceRoute: typeof ConceptsGlitchTraceRoute
  ConceptsGlitchIndexRoute: typeof ConceptsGlitchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/glitch/': {
      id: '/concepts/glitch/'
      path: '/concepts/glitch'
      fullPath: '/concepts/glitch/'
      preLoaderRoute: typeof ConceptsGlitchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/glitch/field': {
      id: '/concepts/glitch/field'
      path: '/concepts/glitch/field'
      fullPath: '/concepts/glitch/field'
      preLoaderRoute: typeof ConceptsGlitchFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/glitch/shards': {
      id: '/concepts/glitch/shards'
      path: '/concepts/glitch/shards'
      fullPath: '/concepts/glitch/shards'
      preLoaderRoute: typeof ConceptsGlitchShardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/glitch/trace': {
      id: '/concepts/glitch/trace'
      path: '/concepts/glitch/trace'
      fullPath: '/concepts/glitch/trace'
      preLoaderRoute: typeof ConceptsGlitchTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  ConceptsGlitchFieldRoute: ConceptsGlitchFieldRoute,
  ConceptsGlitchShardsRoute: ConceptsGlitchShardsRoute,
  ConceptsGlitchTraceRoute: ConceptsGlitchTraceRoute,
  ConceptsGlitchIndexRoute: ConceptsGlitchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
